import { supabase } from "./supabaseClient";
export type DbTransaction={id:string;sender_wallet_id:string|null;receiver_wallet_id:string|null;amount:number|string;currency:string;type:string;status:string;description:string|null;reference:string|null;created_at:string};
export type DbPaymentMethod={id:string;method_type:string;provider:string;account_label:string|null;last4:string|null;is_default:boolean;created_at:string};
export type DbProfile={id:string;full_name:string|null;phone:string|null;avatar_url:string|null;created_at:string;updated_at:string};
export type KycDocumentType="nid"|"passport"|"driving-license";
export type DbKycSubmission={id:string;user_id:string;full_name:string;date_of_birth:string;address:string;document_type:KycDocumentType;document_number:string;front_path:string;back_path:string|null;selfie_path:string;status:"pending"|"verified"|"rejected";reviewer_note:string|null;created_at:string;updated_at:string};
export type DbPaymentRequest={id:string;requester_user_id:string;recipient_user_id:string;amount:number|string;currency:string;note:string|null;status:"pending"|"paid"|"declined"|"expired";created_at:string;updated_at:string;paid_at:string|null};
export type PaymentRequestPayment={transaction_id:string;reference:string;request_id:string;amount:number|string;status:"paid"};
export type DbNotification={id:string;user_id:string;title:string;message:string;is_read:boolean;created_at:string;type?:string};\nexport type DbProviderPayment={id:string;user_id:string;payment_method_id:string;provider:string;provider_mode:"mock"|"live";direction:"add_money"|"withdraw";amount:number|string;currency:string;status:"initiated"|"pending"|"approved"|"completed"|"failed"|"cancelled";idempotency_key:string;provider_reference:string;wallet_transaction_id:string|null;created_at:string;updated_at:string;completed_at:string|null};
export async function getCurrentUser(){const{data,error}=await supabase.auth.getUser();if(error)throw error;return data.user;}
export async function getCurrentProfile(){const user=await getCurrentUser();if(!user)return null;const{data,error}=await supabase.from("profiles").select("id,full_name,phone,avatar_url,created_at,updated_at").eq("id",user.id).maybeSingle();if(error)throw error;return data as DbProfile|null;}
export async function updateCurrentProfile(input:{full_name:string;phone?:string|null;avatar_url?:string|null}){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{data,error}=await supabase.from("profiles").update({full_name:input.full_name.trim(),phone:input.phone?.trim()||null,avatar_url:input.avatar_url?.trim()||null}).eq("id",user.id).select("id,full_name,phone,avatar_url,created_at,updated_at").single();if(error)throw error;return data as DbProfile;}
export async function findProfileByPhone(phone:string){const{data,error}=await supabase.from("profiles").select("id,full_name,phone").eq("phone",phone.trim()).maybeSingle();if(error)throw error;return data as Pick<DbProfile,"id"|"full_name"|"phone">|null;}
export async function createPaymentRequest(recipientPhone:string,amount:number,note?:string){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const recipient=await findProfileByPhone(recipientPhone);if(!recipient)throw new Error("No Payra user was found with that phone number.");if(recipient.id===user.id)throw new Error("You cannot request money from yourself.");const{data,error}=await supabase.from("payment_requests").insert({requester_user_id:user.id,recipient_user_id:recipient.id,amount,currency:"BDT",note:note?.trim()||null}).select("*").single();if(error)throw error;return{request:data as DbPaymentRequest,recipient};}
export async function getMyPaymentRequests(){const user=await getCurrentUser();if(!user)return[] as DbPaymentRequest[];const{data,error}=await supabase.from("payment_requests").select("*").or(`requester_user_id.eq.${user.id},recipient_user_id.eq.${user.id}`).order("created_at",{ascending:false});if(error)throw error;return(data??[])as DbPaymentRequest[];}
export async function payPaymentRequest(requestId:string){const{data,error}=await supabase.rpc("pay_payment_request",{p_request_id:requestId});if(error)throw error;return data as PaymentRequestPayment;}
export async function getMyNotifications(){const user=await getCurrentUser();if(!user)return[] as DbNotification[];const{data,error}=await supabase.from("notifications").select("id,user_id,title,message,is_read,created_at").eq("user_id",user.id).order("created_at",{ascending:false});if(error)throw error;return(data??[])as DbNotification[];}
export async function markNotificationRead(id:string){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{error}=await supabase.from("notifications").update({is_read:true}).eq("id",id).eq("user_id",user.id);if(error)throw error;}
export async function markAllNotificationsRead(){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{error}=await supabase.from("notifications").update({is_read:true}).eq("user_id",user.id).eq("is_read",false);if(error)throw error;}
export async function uploadKycDocument(file:File,slot:"front"|"back"|"selfie"){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");if(file.size>10*1024*1024)throw new Error("Each document must be 10 MB or smaller.");if(!file.type.startsWith("image/"))throw new Error("Upload an image file.");const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`${user.id}/${crypto.randomUUID()}-${slot}.${ext}`;const{error}=await supabase.storage.from("kyc-documents").upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return path;}
export async function createKycSubmission(input:{full_name:string;date_of_birth:string;address:string;document_type:KycDocumentType;document_number:string;front_path:string;back_path?:string|null;selfie_path:string}){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{data,error}=await supabase.from("kyc_submissions").insert({user_id:user.id,...input,back_path:input.back_path??null}).select("*").single();if(error)throw error;return data as DbKycSubmission;}
export async function getMyLatestKycSubmission(){const user=await getCurrentUser();if(!user)return null;const{data,error}=await supabase.from("kyc_submissions").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data as DbKycSubmission|null;}
export async function getCurrentWallet(){const user=await getCurrentUser();if(!user)return null;const{data,error}=await supabase.from("wallets").select("id,user_id,currency,balance,created_at,updated_at").eq("user_id",user.id).eq("currency","BDT").maybeSingle();if(error)throw error;return data;}
export async function getMyTransactions(limit=50){const wallet=await getCurrentWallet();if(!wallet)return[]as DbTransaction[];const{data,error}=await supabase.from("transactions").select("id,sender_wallet_id,receiver_wallet_id,amount,currency,type,status,description,reference,created_at").or(`sender_wallet_id.eq.${wallet.id},receiver_wallet_id.eq.${wallet.id}`).order("created_at",{ascending:false}).limit(limit);if(error)throw error;return(data??[])as DbTransaction[];}
export async function getMyPaymentMethods(){const user=await getCurrentUser();if(!user)return[]as DbPaymentMethod[];const{data,error}=await supabase.from("payment_methods").select("id,method_type,provider,account_label,last4,is_default,created_at").eq("user_id",user.id).order("is_default",{ascending:false}).order("created_at",{ascending:false});if(error)throw error;return(data??[])as DbPaymentMethod[];}
export async function createPaymentMethod(input:{method_type:string;provider:string;account_label?:string|null;last4?:string|null}){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{data,error}=await supabase.from("payment_methods").insert({user_id:user.id,method_type:input.method_type,provider:input.provider,account_label:input.account_label??null,last4:input.last4??null}).select("id,method_type,provider,account_label,last4,is_default,created_at").single();if(error)throw error;return data as DbPaymentMethod;}
export async function removePaymentMethod(id:string){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{error}=await supabase.from("payment_methods").delete().eq("id",id).eq("user_id",user.id);if(error)throw error;}
export async function setDefaultPaymentMethod(id:string){const user=await getCurrentUser();if(!user)throw new Error("You must be signed in.");const{error:clearError}=await supabase.from("payment_methods").update({is_default:false}).eq("user_id",user.id);if(clearError)throw clearError;const{error}=await supabase.from("payment_methods").update({is_default:true}).eq("id",id).eq("user_id",user.id);if(error)throw error;}
export async function sendMoney(recipientPhone:string,amount:number,description?:string){const{data,error}=await supabase.rpc("payra_transfer",{p_recipient_phone:recipientPhone,p_amount:amount,p_description:description??null});if(error)throw error;return data as DbTransaction;}
export async function initiateProviderPayment(paymentMethodId:string,amount:number,direction:"add_money"|"withdraw",idempotencyKey=crypto.randomUUID()){const{data,error}=await supabase.rpc("initiate_provider_payment",{p_payment_method_id:paymentMethodId,p_amount:amount,p_direction:direction,p_idempotency_key:idempotencyKey});if(error)throw error;return data as DbProviderPayment;}\nexport async function completeMockProviderPayment(providerPaymentId:string,approved=true){const{data,error}=await supabase.rpc("complete_mock_provider_payment",{p_provider_payment_id:providerPaymentId,p_approved:approved});if(error)throw error;return data as DbProviderPayment;}\nexport async function getProviderPayment(id:string){const{data,error}=await supabase.from("provider_payments").select("*").eq("id",id).maybeSingle();if(error)throw error;return data as DbProviderPayment|null;}\nexport async function addMoney(amount:number,paymentMethodId:string){const{data,error}=await supabase.rpc("payra_add_money",{p_amount:amount,p_payment_method_id:paymentMethodId});if(error)throw error;return data as DbTransaction;}
export async function withdrawMoney(amount:number,paymentMethodId:string){const{data,error}=await supabase.rpc("payra_withdraw",{p_amount:amount,p_payment_method_id:paymentMethodId});if(error)throw error;return data as DbTransaction;}
export function transactionAmount(tx:DbTransaction,walletId:string){const amount=Number(tx.amount);return tx.receiver_wallet_id===walletId?amount:-amount;}
export function transactionKind(tx:DbTransaction,walletId:string){if(tx.receiver_wallet_id===walletId)return"received"as const;if(tx.type==="withdrawal")return"withdrawal"as const;if(tx.type==="add-money"||tx.type==="topup")return"add-money"as const;if(tx.type==="payment")return"payment"as const;return"sent"as const;}