import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Bell, CheckCheck, CreditCard, ShieldCheck, Wallet } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/payra/app-shell";
import { SoftButton, SurfaceCard } from "@/components/payra/ui-kit";
import { getCurrentUser, getMyNotifications, markAllNotificationsRead, markNotificationRead, type DbNotification } from "@/lib/supabase-data";
import { supabase } from "@/lib/supabaseClient";
import { cn } from "@/lib/utils";
export const Route=createFileRoute("/notifications")({head:()=>({meta:[{title:"Notifications — Payra"},{name:"description",content:"Review your Payra payment and security alerts."}]}),component:NotificationsPage});
const icons={payment:CreditCard,received:Wallet,security:ShieldCheck,request:Bell} as const;
function NotificationsPage(){const[items,setItems]=useState<DbNotification[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busyId,setBusyId]=useState<string|null>(null),[allBusy,setAllBusy]=useState(false);
async function load(){setLoading(true);setError("");try{setItems(await getMyNotifications());}catch(e){setError(e instanceof Error?e.message:"Unable to load notifications.");}finally{setLoading(false);}}
useEffect(()=>{let channel:any;let active=true;(async()=>{try{const user=await getCurrentUser();if(!active||!user)return;await load();channel=supabase.channel("payra-notifications-"+user.id).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:"user_id=eq."+user.id},()=>{void load();}).subscribe();}catch(e){if(active){setError(e instanceof Error?e.message:"Unable to start notifications.");setLoading(false);}}})();return()=>{active=false;if(channel)void supabase.removeChannel(channel);};},[]);
async function read(id:string){setBusyId(id);try{await markNotificationRead(id);setItems(current=>current.map(item=>item.id===id?{...item,is_read:true}:item));}catch(e){toast.error(e instanceof Error?e.message:"Unable to mark notification as read.");}finally{setBusyId(null);}}
async function readAll(){setAllBusy(true);try{await markAllNotificationsRead();setItems(current=>current.map(item=>({...item,is_read:true})));toast.success("All notifications marked as read.");}catch(e){toast.error(e instanceof Error?e.message:"Unable to update notifications.");}finally{setAllBusy(false);}}
const unread=items.filter(x=>!x.is_read).length;
return <AppShell title="Notifications" subtitle="Real-time payments, requests and security updates."><SurfaceCard className="mx-auto max-w-3xl p-2"><div className="flex items-center justify-between gap-3 border-b border-border px-4 py-3"><p className="text-sm text-muted-foreground">{unread?unread+" unread notification"+(unread===1?"":"s"):"You're all caught up"}</p><SoftButton disabled={!unread||allBusy} onClick={()=>void readAll()}><CheckCheck className="size-4"/>{allBusy?"Saving...":"Mark all as read"}</SoftButton></div>{loading?<p className="p-4 text-sm text-muted-foreground">Loading notifications...</p>:error?<div className="p-4"><p className="text-sm text-destructive">{error}</p><SoftButton className="mt-3" onClick={()=>void load()}>Retry</SoftButton></div>:items.length===0?<p className="p-8 text-center text-sm text-muted-foreground">No notifications yet.</p>:<div className="divide-y divide-border">{items.map(item=>{const key=(item.type&&item.type in icons?item.type:"payment")as keyof typeof icons;const Icon=icons[key];return <div key={item.id} className={cn("flex gap-4 rounded-xl p-4",!item.is_read&&"bg-accent/60")}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-card"><Icon className="size-5 text-primary"/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold text-foreground">{item.title}</p><span className="shrink-0 text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"})}</span></div><p className="mt-1 text-sm text-muted-foreground">{item.message}</p>{!item.is_read&&<button type="button" disabled={busyId===item.id} onClick={()=>void read(item.id)} className="mt-2 text-xs font-semibold text-primary hover:underline disabled:opacity-50">{busyId===item.id?"Saving…":"Mark as read"}</button>}</div>{!item.is_read&&<span className="mt-2 size-2 shrink-0 rounded-full bg-primary"/>}</div>;})}</div>}</SurfaceCard></AppShell>;}
