import { useEffect, useState } from "react";
import { Building2, CreditCard, Plus, Smartphone, Trash2 } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { toast } from "sonner";
import { AppShell } from "@/components/payra/app-shell";
import { PaymentSourceCard } from "@/components/payra/cards";
import { EmptyState, ErrorState, ListSkeleton, SectionHeading, SoftButton, SurfaceCard } from "@/components/payra/ui-kit";
import { SubmitButton } from "@/components/payra/flow-kit";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { getMyPaymentMethods, removePaymentMethod, setDefaultPaymentMethod, type DbPaymentMethod } from "@/lib/supabase-data";

export const Route=createFileRoute("/sources/")({head:()=>({meta:[{title:"Payment Sources — Payra"},{name:"description",content:"Manage the banks, cards and wallets connected to Payra."}]}),component:SourcesPage});
const connectOptions=[{kind:"bank",label:"Bank account",detail:"Fund and withdraw",icon:Building2},{kind:"card",label:"Debit / credit card",detail:"Instant top-ups",icon:CreditCard},{kind:"mfs",label:"Mobile wallet",detail:"bKash, Nagad, Rocket",icon:Smartphone}] as const;
function toCard(source:DbPaymentMethod){return {id:source.id,kind:source.method_type,name:source.provider,details:source.account_label||`•••• ${source.last4??""}`,isDefault:source.is_default};}
function SourcesPage(){const [sources,setSources]=useState<DbPaymentMethod[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [pending,setPending]=useState<DbPaymentMethod|null>(null);
 const load=async()=>{setLoading(true);setError("");try{setSources(await getMyPaymentMethods());}catch(e){setError(e instanceof Error?e.message:"Unable to load payment sources.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 async function remove(source:DbPaymentMethod){try{await removePaymentMethod(source.id);setPending(null);toast.success(`${source.provider} removed`);await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to remove source.");}}
 async function makeDefault(source:DbPaymentMethod){try{await setDefaultPaymentMethod(source.id);toast.success(`${source.provider} is now your default source`);await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to update default source.");}}
 return <AppShell title="Payment Sources" subtitle="Choose where your Payra payments come from."><div className="mx-auto grid max-w-4xl gap-6"><SurfaceCard className="p-6"><SectionHeading title="Connected accounts" description="Your real linked payment methods."/>{loading?<ListSkeleton rows={3}/>:error?<ErrorState onRetry={load}/>:sources.length===0?<EmptyState title="No payment sources yet" description="Connect a bank, card or mobile wallet to start moving money."/>:<div className="space-y-3">{sources.map(source=><div key={source.id} className="flex items-center gap-2"><div className="min-w-0 flex-1"><PaymentSourceCard source={toCard(source) as any}/></div>{source.method_type!=="wallet"?<><button type="button" onClick={()=>void makeDefault(source)} disabled={source.is_default} className="rounded-xl border border-border px-3 py-2 text-xs font-semibold disabled:opacity-50">{source.is_default?"Default":"Make default"}</button><button type="button" onClick={()=>setPending(source)} aria-label={`Remove ${source.provider}`} className="grid size-10 shrink-0 place-items-center rounded-xl border border-border text-muted-foreground hover:border-destructive hover:text-destructive"><Trash2 className="size-4" aria-hidden/></button></>:null}</div>)}</div>}</SurfaceCard><SurfaceCard className="p-6"><SectionHeading title="Add a payment source" description="Connect a new account in a few steps."/><div className="grid gap-3 sm:grid-cols-3">{connectOptions.map(({kind,label,detail,icon:Icon})=><Link key={kind} to="/sources/connect/$kind" params={{kind}} className="rounded-2xl border border-border bg-card p-4 hover:bg-accent"><Icon className="size-5 text-primary"/><span className="mt-2 block text-sm font-semibold">{label}</span><span className="block text-xs text-muted-foreground">{detail}</span></Link>)}</div><Link to="/sources/connect/$kind" params={{kind:"bank"}} className="mt-5 block"><SubmitButton className="w-full"><Plus className="size-4"/> Add Payment Source</SubmitButton></Link></SurfaceCard><SurfaceCard className="p-6"><SectionHeading title="Move money" description="Use your connected sources right away."/><div className="grid gap-3 sm:grid-cols-2"><Link to="/add-money"><SoftButton className="w-full">Add money</SoftButton></Link><Link to="/withdraw"><SoftButton className="w-full">Withdraw</SoftButton></Link></div></SurfaceCard></div><AlertDialog open={pending!==null} onOpenChange={open=>!open&&setPending(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {pending?.provider}?</AlertDialogTitle><AlertDialogDescription>This removes the linked payment method from your Payra account.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep source</AlertDialogCancel><AlertDialogAction onClick={()=>pending&&void remove(pending)}>Remove</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></AppShell>;
}