import { useState } from "react";
import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Building2, CreditCard, Smartphone } from "lucide-react";
import { z } from "zod";
import { toast } from "sonner";
import { AppShell } from "@/components/payra/app-shell";
import { EmptyState, SectionHeading, SoftButton, SuccessState, SurfaceCard, TrustBadges } from "@/components/payra/ui-kit";
import { FlowActions, StepTracker, SubmitButton, SummaryList, TextField } from "@/components/payra/flow-kit";
import { createPaymentMethod } from "@/lib/supabase-data";
const connectKinds=["bank","card","mfs"] as const; type ConnectKind=(typeof connectKinds)[number];
function isConnectKind(value:string):value is ConnectKind{return (connectKinds as readonly string[]).includes(value);}
export const Route=createFileRoute("/sources/connect/$kind")({loader:({params})=>{if(!isConnectKind(params.kind))throw notFound();return {kind:params.kind};},head:({loaderData})=>{if(!loaderData)return {meta:[{title:"Source not found — Payra"}]};const label=kindConfig[loaderData.kind].title;return {meta:[{title:`${label} — Payra`},{name:"description",content:kindConfig[loaderData.kind].description}]};},notFoundComponent:UnknownKind,component:ConnectSourcePage});
type FieldDef={id:string;label:string;placeholder:string;schema:z.ZodType<string>;type?:string};
const kindConfig:Record<ConnectKind,{title:string;description:string;icon:typeof Building2;providers:string[];fields:FieldDef[]}>= {
 bank:{title:"Connect a bank account",description:"Link a Bangladeshi bank account to fund and withdraw from Payra.",icon:Building2,providers:["BRAC Bank","City Bank","Dutch-Bangla Bank","Eastern Bank"],fields:[{id:"accountName",label:"Account holder name",placeholder:"Account holder name",schema:z.string().trim().min(3).max(100)},{id:"accountNumber",label:"Account number",placeholder:"Account number",schema:z.string().trim().regex(/^[0-9 ]{10,20}$/)} ,{id:"branch",label:"Branch",placeholder:"Branch name",schema:z.string().trim().min(3).max(100)}]},
 card:{title:"Add a debit or credit card",description:"Add a Visa or Mastercard to top up your Payra wallet.",icon:CreditCard,providers:["Visa","Mastercard","American Express"],fields:[{id:"cardName",label:"Name on card",placeholder:"Name on card",schema:z.string().trim().min(3).max(100)},{id:"cardNumber",label:"Card number",placeholder:"Card number",schema:z.string().trim().regex(/^[0-9 ]{13,23}$/)},{id:"expiry",label:"Expiry (MM/YY)",placeholder:"MM/YY",schema:z.string().trim().regex(/^(0[1-9]|1[0-2])\/\d{2}$/)},{id:"cvc",label:"CVC",placeholder:"CVC",type:"password",schema:z.string().trim().regex(/^\d{3,4}$/)}]},
 mfs:{title:"Link a mobile wallet",description:"Connect bKash, Nagad or Rocket to move money with Payra.",icon:Smartphone,providers:["bKash","Nagad","Rocket","Upay"],fields:[{id:"walletNumber",label:"Wallet number",placeholder:"01XXXXXXXXX",schema:z.string().trim().regex(/^01[3-9][0-9 ]{8,10}$/)},{id:"accountName",label:"Account holder name",placeholder:"Account holder name",schema:z.string().trim().min(3).max(100)}]}}
const steps=["Provider","Details","Confirm"] as const;
function ConnectSourcePage(){const {kind}=Route.useLoaderData();const config=kindConfig[kind];const Icon=config.icon;const [step,setStep]=useState(0);const [provider,setProvider]=useState(config.providers[0]??"");const [values,setValues]=useState<Record<string,string>>({});const [errors,setErrors]=useState<Record<string,string>>({});const [saving,setSaving]=useState(false);const [success,setSuccess]=useState(false);
 function validate(){const next:Record<string,string>={};for(const field of config.fields){const parsed=field.schema.safeParse(values[field.id]??"");if(!parsed.success)next[field.id]=parsed.error.issues[0]?.message??"Invalid value.";}setErrors(next);return Object.keys(next).length===0;}
 async function connect(){if(!validate())return;setSaving(true);try{const raw=values.accountNumber??values.cardNumber??values.walletNumber??"";const digits=raw.replace(/\D/g,"");const accountLabel=values.accountName??values.cardName??null;await createPaymentMethod({method_type:kind,provider,account_label:accountLabel,last4:digits.slice(-4)||null});setSuccess(true);toast.success("Payment source connected");}catch(e){toast.error(e instanceof Error?e.message:"Unable to connect payment source");}finally{setSaving(false);}}
 const masked=(()=>{const raw=values.accountNumber??values.cardNumber??values.walletNumber??"";const digits=raw.replace(/\D/g,"");return digits?`•••• ${digits.slice(-4)}`:"—";})();
 if(success)return <AppShell title={config.title}><SurfaceCard className="mx-auto max-w-2xl p-7"><SuccessState title="Source connected" description={`${provider} is now saved in your Payra account.`}/><SummaryList className="mt-6" rows={[{label:"Provider",value:provider},{label:"Identifier",value:masked},{label:"Status",value:"Active"}]}/><FlowActions><Link to="/sources"><SubmitButton className="w-full sm:w-auto">Back to sources</SubmitButton></Link><Link to="/add-money"><SoftButton className="w-full sm:w-auto">Add money now</SoftButton></Link></FlowActions></SurfaceCard></AppShell>;
 return <AppShell title={config.title} subtitle={config.description}><SurfaceCard className="mx-auto max-w-2xl p-6 sm:p-7"><StepTracker steps={steps} current={step}/>{step===0?<div className="space-y-5"><SectionHeading title="Select a provider" description="Choose the provider for this payment source."/><fieldset><legend className="sr-only">Provider</legend><div className="grid gap-2 sm:grid-cols-2">{config.providers.map(item=><label key={item} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 ${provider===item?"border-primary bg-accent":"border-border bg-card"}`}><input type="radio" name="provider" checked={provider===item} onChange={()=>setProvider(item)} className="size-4"/><Icon className="size-5 text-primary"/><span className="text-sm font-semibold">{item}</span></label>)}</div></fieldset><FlowActions><Link to="/sources"><SoftButton><ArrowLeft className="size-4"/>Cancel</SoftButton></Link><SubmitButton onClick={()=>setStep(1)}>Continue</SubmitButton></FlowActions></div>:null}{step===1?<form className="space-y-4" noValidate onSubmit={e=>{e.preventDefault();if(validate())setStep(2)}}><SectionHeading title={`${provider} details`} description="Only masked identifiers are saved. Never store card CVC or full card numbers."/>{config.fields.map(field=><TextField key={field.id} id={field.id} label={field.label} placeholder={field.placeholder} type={field.type??"text"} value={values[field.id]??""} error={errors[field.id]} onChange={e=>setValues(prev=>({...prev,[field.id]:e.target.value}))}/>)}<FlowActions><SoftButton onClick={()=>setStep(0)}><ArrowLeft className="size-4"/>Back</SoftButton><SubmitButton type="submit">Review</SubmitButton></FlowActions></form>:null}{step===2?<div className="space-y-5"><SectionHeading title="Confirm connection" description="Your source will be saved as a masked payment method."/><SummaryList rows={[{label:"Provider",value:provider},{label:"Identifier",value:masked},{label:"Status",value:"Ready"}]}/><TrustBadges/><FlowActions><SoftButton onClick={()=>setStep(1)}><ArrowLeft className="size-4"/>Back</SoftButton><SubmitButton onClick={()=>void connect()} disabled={saving}>{saving?"Saving…":"Connect source"}</SubmitButton></FlowActions></div>:null}</SurfaceCard></AppShell>}
function UnknownKind(){return <AppShell title="Unknown source type"><SurfaceCard className="mx-auto max-w-2xl p-7"><EmptyState title="Source type not found" description="Choose bank, card or mobile wallet from payment sources."/><FlowActions><Link to="/sources"><SubmitButton>Back to sources</SubmitButton></Link></FlowActions></SurfaceCard></AppShell>}
