/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddMoneyRouteImport } from './routes/add-money'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SendRouteImport } from './routes/send'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as SourcesConnectKindRouteImport } from './routes/sources.connect.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyRoute = AddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesConnectKindRoute = SourcesConnectKindRouteImport.update({
  id: '/connect/$kind',
  path: '/connect/$kind',
  getParentRoute: () => SourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/request': typeof RequestRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/withdraw': typeof WithdrawRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/sources/connect/$kind': typeof SourcesConnectKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/request': typeof RequestRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/withdraw': typeof WithdrawRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions': typeof TransactionsIndexRoute
  '/sources/connect/$kind': typeof SourcesConnectKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/request': typeof RequestRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/withdraw': typeof WithdrawRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/sources/connect/$kind': typeof SourcesConnectKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-money'
    | '/dashboard'
    | '/forgot-password'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/receive'
    | '/request'
    | '/scan'
    | '/send'
    | '/settings'
    | '/signup'
    | '/sources'
    | '/verify-otp'
    | '/withdraw'
    | '/transactions/$id'
    | '/transactions/'
    | '/sources/connect/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-money'
    | '/dashboard'
    | '/forgot-password'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/receive'
    | '/request'
    | '/scan'
    | '/send'
    | '/settings'
    | '/signup'
    | '/sources'
    | '/verify-otp'
    | '/withdraw'
    | '/transactions/$id'
    | '/transactions'
    | '/sources/connect/$kind'
  id:
    | '__root__'
    | '/'
    | '/add-money'
    | '/dashboard'
    | '/forgot-password'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/receive'
    | '/request'
    | '/scan'
    | '/send'
    | '/settings'
    | '/signup'
    | '/sources'
    | '/verify-otp'
    | '/withdraw'
    | '/transactions/$id'
    | '/transactions/'
    | '/sources/connect/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMoneyRoute: typeof AddMoneyRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReceiveRoute: typeof ReceiveRoute
  RequestRoute: typeof RequestRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  VerifyOtpRoute: typeof VerifyOtpRoute
  WithdrawRoute: typeof WithdrawRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money': {
      id: '/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/connect/$kind': {
      id: '/sources/connect/$kind'
      path: '/connect/$kind'
      fullPath: '/sources/connect/$kind'
      preLoaderRoute: typeof SourcesConnectKindRouteImport
      parentRoute: typeof SourcesRoute
    }
  }
}

interface SourcesRouteChildren {
  SourcesConnectKindRoute: typeof SourcesConnectKindRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesConnectKindRoute: SourcesConnectKindRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMoneyRoute: AddMoneyRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReceiveRoute: ReceiveRoute,
  RequestRoute: RequestRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SourcesRoute: SourcesRouteWithChildren,
  VerifyOtpRoute: VerifyOtpRoute,
  WithdrawRoute: WithdrawRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
